#ifndef WEBINTERFACE_H
#define WEBINTERFACE_H

#include "main.h"

// Forward declaration for robot config
extern RobotConfig robotConfig;

// Navigation bar HTML
String navBar(const char* activeTab) {
  String activeStyle = "background: #4CAF50; color: white;";
  String inactiveStyle = "background: #333; color: white;";
  
  return "<nav style='background:#333;padding:15px;margin-bottom:20px;'>"
         "<a href='/' style='color:white;text-decoration:none;padding:10px 20px;margin:5px;border-radius:5px;" + 
         String(strcmp(activeTab, "control") == 0 ? activeStyle : inactiveStyle) + "'>Control</a>"
         "<a href='/kinematics' style='color:white;text-decoration:none;padding:10px 20px;margin:5px;border-radius:5px;" +
         String(strcmp(activeTab, "kinematics") == 0 ? activeStyle : inactiveStyle) + "'>Cinemática Inversa</a>"
         "</nav>";
}

// HTML Page generation function
String htmlPage(const LegAngles& currentLeftLeg, const LegAngles& currentRightLeg) {
  return "<!DOCTYPE html>"
         "<html>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<title>Control Humanoide</title>"
         "<style>"
         "body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);min-height:100vh;margin:0;}"
         ".container{max-width:1200px;margin:0 auto;padding:20px;}"
         ".main-box{background:white;border-radius:15px;padding:30px;box-shadow:0 10px 30px rgba(0,0,0,0.3);}"
         ".dpad{display:inline-block;margin:20px;}"
         ".row{display:flex;justify-content:center;}"
         "button{width:80px;height:80px;margin:5px;font-size:20px;border:none;border-radius:10px;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         "button:hover{transform:scale(1.1);}"
         ".form-section{margin-top:30px;background:#f8f9fa;padding:25px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1);}"
         ".form-section h3{color:#333;margin-top:0;padding-bottom:15px;border-bottom:3px solid #0066cc;}"
         ".form-section h4{color:#0066cc;margin:20px 0 10px 0;font-size:18px;}"
         ".input-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:15px;margin:20px 0;}"
         ".input-group{display:flex;flex-direction:column;}"
         ".input-group label{font-weight:600;color:#333;margin-bottom:8px;font-size:14px;}"
         ".input-group input{padding:12px;border:2px solid #ddd;border-radius:8px;font-size:16px;transition:border-color 0.2s;}"
         ".input-group input:focus{outline:none;border-color:#0066cc;}"
         "input[type='submit']{background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;border:none;padding:15px 40px;font-size:18px;border-radius:8px;cursor:pointer;transition:transform 0.2s;margin-top:15px;}"
         "input[type='submit']:hover{transform:scale(1.05);}"
         "h2{color:#333;margin:20px 0;}"
         ".centered{text-align:center;}"
         ".reset-btn{background:linear-gradient(135deg,#ff6b6b 0%,#cc0000 100%);width:auto;padding:15px 30px;font-size:16px;margin:20px auto;display:block;border:none;border-radius:8px;color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         ".reset-btn:hover{transform:scale(1.05);}"
         "</style>"
         "<script>"
         "document.addEventListener('keydown', function(e){"
         "  if(e.key==='w'){ window.location.href='/forward'; }"
         "  else if(e.key==='s'){ window.location.href='/backward'; }"
         "  else if(e.key==='a'){ window.location.href='/left'; }"
         "  else if(e.key==='d'){ window.location.href='/right'; }"
         "});"
         "</script>"
         "</head>"
         "<body>"
         + navBar("control") +
         "<div class='container'>"
         "<div class='main-box'>"
         "<h2 class='centered'>Control de Humanoide</h2>"
         "<div class='centered'>"
         "<div class='dpad'>"
         "<div class='row'><button onclick=\"location.href='/forward'\">&#9650;</button></div>"
         "<div class='row'><button onclick=\"location.href='/left'\">&#9664;</button>"
         "<button onclick=\"location.href='/right'\">&#9654;</button></div>"
         "<div class='row'><button onclick=\"location.href='/backward'\">&#9660;</button></div>"
         "</div>"
         "</div>"
         "<button class='reset-btn' onclick=\"location.href='/reset?from=control'\">Reset a Posición Neutral</button>"
         "<form action='/setservos' method='GET' class='form-section'>"
         "<h3>Posiciones de Servos (0°–180°)</h3>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Hip L:</label><input type='number' name='hipL' min='0' max='180' value='" + String(currentLeftLeg.hip) + "'></div>"
         "<div class='input-group'><label>Knee L:</label><input type='number' name='kneeL' min='0' max='180' value='" + String(currentLeftLeg.knee) + "'></div>"
         "<div class='input-group'><label>Ankle L:</label><input type='number' name='ankleL' min='0' max='180' value='" + String(currentLeftLeg.ankle) + "'></div>"
         "<div class='input-group'><label>Hip R:</label><input type='number' name='hipR' min='0' max='180' value='" + String(currentRightLeg.hip) + "'></div>"
         "<div class='input-group'><label>Knee R:</label><input type='number' name='kneeR' min='0' max='180' value='" + String(currentRightLeg.knee) + "'></div>"
         "<div class='input-group'><label>Ankle R:</label><input type='number' name='ankleR' min='0' max='180' value='" + String(currentRightLeg.ankle) + "'></div>"
         "</div>"
         "<div class='centered'><input type='submit' value='Actualizar'></div>"
         "</form>"
         "<form action='/setconfig' method='GET' class='form-section'>"
         "<h3>Configuración del Robot</h3>"
         "<h4>Offsets (0°–180°)</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Hip L Offset:</label><input type='number' name='hipLOffset' min='0' max='180' value='" + String(robotConfig.hipLOffset) + "'></div>"
         "<div class='input-group'><label>Knee L Offset:</label><input type='number' name='kneeLOffset' min='0' max='180' value='" + String(robotConfig.kneeLOffset) + "'></div>"
         "<div class='input-group'><label>Ankle L Offset:</label><input type='number' name='ankleLOffset' min='0' max='180' value='" + String(robotConfig.ankleLOffset) + "'></div>"
         "<div class='input-group'><label>Hip R Offset:</label><input type='number' name='hipROffset' min='0' max='180' value='" + String(robotConfig.hipROffset) + "'></div>"
         "<div class='input-group'><label>Knee R Offset:</label><input type='number' name='kneeROffset' min='0' max='180' value='" + String(robotConfig.kneeROffset) + "'></div>"
         "<div class='input-group'><label>Ankle R Offset:</label><input type='number' name='ankleROffset' min='0' max='180' value='" + String(robotConfig.ankleROffset) + "'></div>"
         "</div>"
         "<h4>Geometría de Piernas (cm)</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>L1 (Upper Leg):</label><input type='number' name='l1' min='0.1' max='20.0' step='0.1' value='" + String(robotConfig.l1) + "'></div>"
         "<div class='input-group'><label>L2 (Lower Leg):</label><input type='number' name='l2' min='0.1' max='20.0' step='0.1' value='" + String(robotConfig.l2) + "'></div>"
         "</div>"
         "<h4>Parámetros de Paso</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Step Clearance:</label><input type='number' name='stepClearance' min='0.1' max='10.0' step='0.1' value='" + String(robotConfig.stepClearance) + "'></div>"
         "<div class='input-group'><label>Step Height:</label><input type='number' name='stepHeight' min='1.0' max='20.0' step='0.1' value='" + String(robotConfig.stepHeight) + "'></div>"
         "<div class='input-group'><label>Step Length:</label><input type='number' name='stepLength' min='0.5' max='10.0' step='0.1' value='" + String(robotConfig.stepLength) + "'></div>"
         "<div class='input-group'><label>Step Velocity:</label><input type='number' name='stepVelocity' min='1' max='500' step='1' value='" + String(robotConfig.stepVelocity) + "'></div>"
         "<div class='input-group'><label>Step Offset:</label><input type='number' name='stepOffset' min='-5.0' max='5.0' step='0.1' value='" + String(robotConfig.stepOffset) + "'></div>"
         "<div class='input-group'><label>Number of Steps:</label><input type='number' name='numSteps' min='1' max='50' step='1' value='" + String(robotConfig.numSteps) + "'></div>"
         "</div>"
         "<div class='centered'><input type='submit' value='Actualizar'></div>"
         "</form>"
         "</div>"
         "</div>"
         "</body>"
         "</html>";
}

// Tutorial Kinematics Page
String htmlKinematicsPage() {
  return "<!DOCTYPE html>"
         "<html>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<title>Tutorial de Cinemática - Humanoide</title>"
         "<style>"
         "body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);min-height:100vh;margin:0;}"
         ".container{max-width:1200px;margin:0 auto;padding:20px;}"
         ".main-box{background:white;border-radius:15px;padding:30px;box-shadow:0 10px 30px rgba(0,0,0,0.3);}"
         ".dpad{display:inline-block;margin:20px;}"
         ".row{display:flex;justify-content:center;}"
         "button{width:80px;height:80px;margin:5px;font-size:20px;border:none;border-radius:10px;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         "button:hover{transform:scale(1.1);}"
         ".reset-btn{background:linear-gradient(135deg,#ff6b6b 0%,#cc0000 100%);width:auto;padding:15px 30px;font-size:16px;margin:20px auto;display:block;border:none;border-radius:8px;color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         ".reset-btn:hover{transform:scale(1.05);}"
         ".centered{text-align:center;}"
         ".data-section{margin-top:30px;background:#f8f9fa;border-radius:10px;padding:25px;}"
         ".data-section h3{color:#333;margin-top:0;border-bottom:2px solid #0066cc;padding-bottom:10px;}"
         ".leg-table{width:100%;margin:20px 0;border-collapse:collapse;background:white;border-radius:8px;overflow:hidden;}"
         ".leg-table th{background:#0066cc;color:white;padding:12px;text-align:left;font-weight:600;}"
         ".leg-table td{padding:10px 12px;border-bottom:1px solid #e0e0e0;}"
         ".leg-table tr:last-child td{border-bottom:none;}"
         ".leg-table tr:nth-child(even){background:#f9f9f9;}"
         ".value-cell{font-weight:bold;color:#333;font-family:'Courier New',monospace;}"
         ".calc-cell{font-size:12px;color:#666;font-style:italic;}"
         ".angle-formula{font-family:'Courier New',monospace;font-size:13px;}"
         ".angle-formula .offset-part{color:#999;font-style:italic;font-weight:normal;}"
         ".process-boxes{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px;margin-top:20px;}"
         ".process-box{background:white;padding:20px;border-radius:8px;border-left:5px solid #0066cc;box-shadow:0 2px 8px rgba(0,0,0,0.1);}"
         ".process-box h4{color:#0066cc;margin:0 0 12px 0;font-size:16px;border-bottom:2px solid #e0e0e0;padding-bottom:8px;}"
         ".process-box p{color:#666;margin:8px 0;font-size:14px;line-height:1.6;}"
         ".process-box .formula{background:#f8f9fa;padding:10px;border-radius:5px;font-family:'Courier New',monospace;font-size:12px;color:#333;margin-top:10px;}"
         ".process-box .highlight{color:#4CAF50;font-weight:600;}"
         "</style>"
         "<script>"
         "document.addEventListener('keydown', function(e){"
         "  if(e.key==='w'){ window.location.href='/forward'; }"
         "  else if(e.key==='s'){ window.location.href='/backward'; }"
         "  else if(e.key==='a'){ window.location.href='/left'; }"
         "  else if(e.key==='d'){ window.location.href='/right'; }"
         "});"
         "</script>"
         "</head>"
         "<body>"
         + navBar("kinematics") +
         "<div class='container'>"
         "<div class='main-box'>"
         "<h1 style='color:#333;text-align:center;margin-bottom:10px;'>Tutorial de Marcha Paso a Paso</h1>"
         "<p style='text-align:center;color:#666;margin-bottom:30px;'>Aprende cómo funciona la cinemática inversa y la marcha bípeda</p>"
         "<div class='centered'>"
         "<button class='step-btn' id='stepForwardBtn' onclick='initStepForward()' style='display:block;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;border:none;padding:20px 50px;font-size:24px;font-weight:bold;border-radius:10px;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);margin:20px auto;min-width:250px;'>Iniciar Paso Adelante (stepForward)</button>"
         "<button class='step-btn' id='nextStepBtn' onclick='executeNextStep()' style='display:none;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;border:none;padding:15px 30px;font-size:16px;font-weight:bold;border-radius:10px;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);margin:20px auto;min-width:250px;'>Ejecutar Siguiente Escritura</button>"
         "</div>"
         "<button class='reset-btn' onclick=\"location.href='/reset?from=kinematics'\" style='background:linear-gradient(135deg,#ff6b6b 0%,#cc0000 100%);width:auto;padding:12px 25px;font-size:14px;margin:20px auto;display:block;border:none;border-radius:8px;color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);'>Reset a Posición Neutral</button>"
         "<div class='tutorial-section' id='tutorialContent' style='margin-top:30px;background:#f8f9fa;border-radius:10px;padding:25px;'>"
         "<div class='waiting' style='text-align:center;color:#666;font-size:18px;padding:40px;'>Presiona 'Iniciar Paso Adelante' para comenzar el tutorial paso a paso</div>"
         "</div>"
         "</div>"
         "</div>"
         "<script>"
         "let currentStepIndex = -1;"
         "let isInitialized = false;"
         "let hipLOffset = " + String(robotConfig.hipLOffset) + ";"
         "let kneeLOffset = " + String(robotConfig.kneeLOffset) + ";"
         "let ankleLOffset = " + String(robotConfig.ankleLOffset) + ";"
         "let hipROffset = " + String(robotConfig.hipROffset) + ";"
         "let kneeROffset = " + String(robotConfig.kneeROffset) + ";"
         "let ankleROffset = " + String(robotConfig.ankleROffset) + ";"
         ""
         "function initStepForward() {"
         "  fetch('/tutorial/init')"
         "    .then(response => response.json())"
         "    .then(data => {"
         "      if (data.success) {"
         "        isInitialized = true;"
         "        currentStepIndex = 0;"
         "        document.getElementById('stepForwardBtn').style.display = 'none';"
         "        document.getElementById('nextStepBtn').style.display = 'block';"
         "        loadCurrentStep();"
         "      }"
         "    })"
         "    .catch(error => console.error('Error:', error));"
         "}"
         ""
         "function loadCurrentStep() {"
         "  fetch('/tutorial/step')"
         "    .then(response => response.json())"
         "    .then(data => {"
         "      if (data.step) {"
         "        displayStep(data.step, data.currentIndex, data.totalSteps);"
         "      } else if (data.complete) {"
         "        displayComplete();"
         "      }"
         "    })"
         "    .catch(error => console.error('Error:', error));"
         "}"
         ""
         "function displayStep(step, index, total) {"
         "  const legName = step.leg === 'l' ? 'Izquierda' : 'Derecha';"
         "  const legClass = step.leg === 'l' ? 'leg-left' : 'leg-right';"
         "  const isLeft = step.leg === 'l';"
         ""
         "  let hipServo, kneeServo, ankleServo;"
         "  if (isLeft) {"
         "    hipServo = hipLOffset - step.angles.hip;"
         "    kneeServo = kneeLOffset - step.angles.knee;"
         "    ankleServo = 2 * ankleLOffset - step.angles.ankle;"
         "  } else {"
         "    hipServo = hipROffset + step.angles.hip;"
         "    kneeServo = kneeROffset + step.angles.knee;"
         "    ankleServo = ankleROffset + step.angles.ankle;"
         "  }"
         ""
         "  const html = \""
         "  <h3>Tutorial: Escritura \" + (index + 1) + \" de \" + total + \"</h3>"
         "  <div class='step-info' style='background:white;border-radius:8px;padding:20px;margin:15px 0;border-left:5px solid #0066cc;box-shadow:0 2px 8px rgba(0,0,0,0.1);'>"
         "    <div class='step-header' style='display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;'>"
         "      <div>"
         "        <span class='step-title' style='font-size:20px;font-weight:bold;color:#0066cc;'>Fase \" + step.phase + \" - Pierna \" + legName + \"</span>"
         "        <span class='leg-indicator \" + legClass + \"' style='display:inline-block;padding:5px 15px;border-radius:20px;color:white;font-weight:bold;margin-left:10px;background:\" + (isLeft ? \"#0066cc\" : \"#4CAF50\") + \";'>\" + legName.toUpperCase() + \"</span>"
         "        <span class='phase-indicator' style='display:inline-block;padding:5px 15px;border-radius:20px;background:#9c27b0;color:white;font-weight:bold;margin-left:10px;'>FASE \" + step.phase + \"</span>"
         "      </div>"
         "      <div class='step-progress' style='color:#666;font-size:14px;'>Escritura \" + step.writeNumber + \"/4 para esta pierna</div>"
         "    </div>"
         "    <div style='background:#e3f2fd;padding:15px;border-radius:8px;margin:15px 0;'>"
         "      <strong>Posición objetivo:</strong> X = \" + step.x.toFixed(2) + \" cm, Z = \" + step.z.toFixed(2) + \" cm"
         "    </div>"
         "    <div class='angle-display' style='display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin:15px 0;'>"
         "      <div class='angle-box' style='background:#f0f7ff;padding:15px;border-radius:8px;border:2px solid #0066cc;'>"
         "        <div class='angle-label' style='font-weight:bold;color:#0066cc;margin-bottom:8px;font-size:14px;'>Hip (Cadera)</div>"
         "        <div class='angle-value' style='font-size:24px;font-weight:bold;color:#333;font-family:Courier New,monospace;'>\" + step.angles.hip.toFixed(1) + \"°</div>"
         "        <div style='font-size:12px;color:#666;margin-top:5px;'>Servo: \" + hipServo.toFixed(0) + \"°</div>"
         "      </div>"
         "      <div class='angle-box' style='background:#f0f7ff;padding:15px;border-radius:8px;border:2px solid #0066cc;'>"
         "        <div class='angle-label' style='font-weight:bold;color:#0066cc;margin-bottom:8px;font-size:14px;'>Knee (Rodilla)</div>"
         "        <div class='angle-value' style='font-size:24px;font-weight:bold;color:#333;font-family:Courier New,monospace;'>\" + step.angles.knee.toFixed(1) + \"°</div>"
         "        <div style='font-size:12px;color:#666;margin-top:5px;'>Servo: \" + kneeServo.toFixed(0) + \"°</div>"
         "      </div>"
         "      <div class='angle-box' style='background:#f0f7ff;padding:15px;border-radius:8px;border:2px solid #0066cc;'>"
         "        <div class='angle-label' style='font-weight:bold;color:#0066cc;margin-bottom:8px;font-size:14px;'>Ankle (Tobillo)</div>"
         "        <div class='angle-value' style='font-size:24px;font-weight:bold;color:#333;font-family:Courier New,monospace;'>\" + step.angles.ankle.toFixed(1) + \"°</div>"
         "        <div style='font-size:12px;color:#666;margin-top:5px;'>Servo: \" + ankleServo.toFixed(0) + \"°</div>"
         "      </div>"
         "    </div>"
         "    <div class='explanation-box' style='background:#fff9e6;border:2px solid #ffc107;border-radius:8px;padding:15px;margin-top:15px;'>"
         "      <div style='margin:0;color:#856404;line-height:1.6;font-size:14px;'>\" + step.angles.explanation + \"</div>"
         "    </div>"
         "    <div style='text-align:center;margin-top:20px;color:#666;font-style:italic;'>"
         "      Presiona 'Ejecutar Siguiente Escritura' para enviar estos comandos a los servos"
         "    </div>"
         "  </div>\";"
         ""
         "  document.getElementById('tutorialContent').innerHTML = html;"
         "}"
         ""
         "function executeNextStep() {"
         "  fetch('/tutorial/execute')"
         "    .then(response => response.json())"
         "    .then(data => {"
         "      if (data.success) {"
         "        setTimeout(() => {"
         "          fetch('/tutorial/advance')"
         "            .then(response => response.json())"
         "            .then(data => {"
         "              if (data.hasMore) {"
         "                loadCurrentStep();"
         "              } else {"
         "                displayComplete();"
         "              }"
         "            });"
         "        }, 500);"
         "      }"
         "    })"
         "    .catch(error => console.error('Error:', error));"
         "}"
         ""
         "function displayComplete() {"
         "  document.getElementById('tutorialContent').innerHTML = \""
         "  <h3>Tutorial Completado</h3>"
         "  <div class='step-info' style='background:white;border-radius:8px;padding:40px;margin:15px 0;border-left:5px solid #0066cc;box-shadow:0 2px 8px rgba(0,0,0,0.1);text-align:center;'>"
         "    <div style='font-size:24px;color:#4CAF50;margin-bottom:20px;'>✓</div>"
         "    <div style='font-size:18px;color:#333;margin-bottom:15px;'>Has completado un paso adelante completo</div>"
         "    <div style='color:#666;'>El robot ha ejecutado todas las 8 escrituras de servo (4 por pierna en 2 fases)</div>"
         "    <button class='reset-btn' onclick='location.reload()' style='margin-top:20px;'>Iniciar Nuevo Tutorial</button>"
         "  </div>\";"
         "  document.getElementById('nextStepBtn').style.display = 'none';"
         "  document.getElementById('stepForwardBtn').style.display = 'block';"
         "  currentStepIndex = -1;"
         "  isInitialized = false;"
         "}"
         "</script>"
         "</body>"
         "</html>";
}

#endif // WEBINTERFACE_H
